name: Varo
version: 0.1
author: clyko & dplat
main: com.varo.Varo

commands:
  start:
    description: Startet Varo
    usage: /<command>
  spawn:
    description: Setzt dies Spawns für die Spieler
    usage: /<command>