name: Varo
version: 0.1
author: Christopher Lyko & Daniel Platkevicius
main: com.varo.Varo
api-version: 1.17

commands:
  start:
    description: Startet Varo
    usage: /<command>
  spawn:
    description: Setzt die Spawns für die Spieler
    usage: /<command>
  generate:
    description: Generiert Spawn
    usage: /<command>
  lootbox:
    description: Setzt den Spawn für eine Lootbox
    usage: /<command>